#!/bin/bash
# build-popular.sh SRC OUT RELEASES [BUDGET_SECONDS] [BATCH_SIZE]
#
# Runs through kernel-configs/popular-priority.tsv (target manifests
# generated by gen-popular-targets.py, ranked by real hardware popularity)
# in batches of BATCH_SIZE (4 by default) via build-batch-jobserver.sh —
# a shared GNU Make jobserver instead of separate processes with a split
# --jobs. Measured empirically: 1 combo at a time ~54s, 2 at once as
# separate processes ~80s (worse, oversubscribed), while through the
# jobserver: 2->46s, 4->38s, 6->14s per combo — the CPU doesn't sit idle
# during one combo's single-threaded link, because the free tokens go
# straight to another combo that's actively compiling.
#
# Does NOT stop on individual failures — just keeps going. Every
# successful build is copied into RELEASES with a readable name +
# description.txt. Stops on its own once BUDGET_SECONDS runs out
# (3 hours = 10800s by default) — checks the budget BEFORE starting each
# new BATCH, never interrupts one already in progress.
set -u
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

SRC="${1:?path to the kernel tree}"
OUT="${2:?build working directory (a srctree per target)}"
RELEASES="${3:?where to put the finished vmlinuz+description}"
BUDGET="${4:-10800}"
BATCH_SIZE="${5:-4}"

PRIO="$HERE/popular-priority.tsv"
[ -f "$PRIO" ] || { echo "$PRIO not found — run gen-popular-targets.py first" >&2; exit 1; }

TOTAL_N=$(( $(wc -l < "$PRIO") - 1 ))

mkdir -p "$OUT" "$RELEASES"
chown tarilka0gg:tarilka0gg "$RELEASES"
STATUS="$RELEASES/status.tsv"
echo -e "rank\tname\tresult\tseconds\tdescription" > "$STATUS"
LOG="$RELEASES/build-popular.log"
: > "$LOG"
chown tarilka0gg:tarilka0gg "$STATUS" "$LOG"

START=$(date +%s)
log(){ echo "$(date '+%F %T') $*" | tee -a "$LOG"; }

log "=== start: budget ${BUDGET}s (~$((BUDGET/3600))h), batch=$BATCH_SIZE, target $RELEASES ==="

harvest_ok(){
    # Called only once the bzImage is confirmed to exist (a batch success,
    # or a successful background retry) — a fast copy, no blocking steps.
    local rank="$1" name="$2" score="$3" desc="$4" dt="$5"
    local bzimg="$OUT/$name/srctree/arch/x86/boot/bzImage"
    local outbase="$RELEASES/${rank}_${name#pop-*-}"
    cp "$bzimg" "$outbase.vmlinuz"
    {
        echo "Kernel: $name"
        echo "Popularity priority: $rank/$TOTAL_N (score=$score)"
        echo "Time: within a batch jobserver build (~${dt}s for the whole batch)"
        echo
        echo "For which hardware:"
        echo "  $desc"
        echo
        echo "kernelrelease: $(cd "$OUT/$name/srctree" && make -s kernelrelease 2>/dev/null)"
    } > "$outbase.txt"
    chown tarilka0gg:tarilka0gg "$outbase.vmlinuz" "$outbase.txt"
    log "  [OK] $name -> $(basename "$outbase.vmlinuz")"
    echo -e "$rank\t$name\tOK\t$dt\t$desc" >> "$STATUS"
    rm -rf "$OUT/$name/srctree"   # free disk right away, vmlinuz is already copied out
}

retry_and_harvest(){
    # A solo retry for a combo that failed within a batch. A batch
    # (jobserver, several combos at once) build sometimes fails from
    # memory pressure / a kallsyms multi-pass race — the combo by itself
    # usually builds fine without neighbors.
    #
    # Runs in the BACKGROUND (& in the call below) with a low --jobs, so
    # it does NOT block the start of the next batch — the retry used to
    # run synchronously and the CPU sat idle waiting on one slow solo
    # build instead of already loading up the next 4 combos.
    local rank="$1" name="$2" score="$3" desc="$4" dt="$5"
    local bzimg="$OUT/$name/srctree/arch/x86/boot/bzImage"
    log "  [RETRY] $name — retrying alone in the background (doesn't block the next batch)"
    rm -rf "$OUT/$name/srctree"
    "$HERE/matrix-build.sh" "$SRC" "$OUT" --target "$name" --build --skip-modules --jobs 4 >>"$LOG" 2>&1
    if [ -f "$bzimg" ]; then
        harvest_ok "$rank" "$name" "$score" "$desc" "$dt"
    else
        log "  [FAIL_NO_BZIMAGE] $name — leaving srctree for diagnostics ($OUT/$name/srctree)"
        echo -e "$rank\t$name\tFAIL_NO_BZIMAGE\t$dt\t$desc" >> "$STATUS"
    fi
}

RETRY_PIDS=()
cap_retries(){
    # Don't let background retries pile up without bound (each is --jobs 4,
    # plus the next batch itself loads -j24 — cap it at 2 concurrent
    # retries, to avoid repeating the oversubscription instability).
    while [ "${#RETRY_PIDS[@]}" -ge 2 ]; do
        wait -n 2>/dev/null
        local alive=()
        for pid in "${RETRY_PIDS[@]}"; do
            kill -0 "$pid" 2>/dev/null && alive+=("$pid")
        done
        RETRY_PIDS=("${alive[@]}")
    done
}

mapfile -t ALL_ROWS < <(tail -n +2 "$PRIO")

i=0
while [ "$i" -lt "${#ALL_ROWS[@]}" ]; do
    now=$(date +%s)
    remaining=$((BUDGET - (now - START)))
    if [ "$remaining" -le 0 ]; then
        log "BUDGET EXHAUSTED — stopping at entry $((i+1))/${#ALL_ROWS[@]}"
        break
    fi

    batch_ranks=(); batch_names=(); batch_scores=(); batch_descs=()
    n=0
    while [ "$n" -lt "$BATCH_SIZE" ] && [ "$i" -lt "${#ALL_ROWS[@]}" ]; do
        IFS=$'\t' read -r rank name score desc <<< "${ALL_ROWS[$i]}"
        i=$((i+1))
        already="$RELEASES/${rank}_${name#pop-*-}.vmlinuz"
        if [ -f "$already" ]; then
            log "[$rank/$TOTAL_N] already done (resume) -> skipping $name"
            continue
        fi
        batch_ranks+=("$rank"); batch_names+=("$name")
        batch_scores+=("$score"); batch_descs+=("$desc")
        n=$((n+1))
    done
    [ "${#batch_names[@]}" -gt 0 ] || continue

    log "=== batch: ${batch_names[*]} ==="
    t0=$(date +%s)
    "$HERE/build-batch-jobserver.sh" "$SRC" "$OUT" "${batch_names[@]}" >>"$LOG" 2>&1
    t1=$(date +%s); dt=$((t1-t0))
    log "=== batch finished in ${dt}s ==="

    for j in "${!batch_names[@]}"; do
        name="${batch_names[$j]}"
        bzimg="$OUT/$name/srctree/arch/x86/boot/bzImage"
        if [ -f "$bzimg" ]; then
            harvest_ok "${batch_ranks[$j]}" "$name" "${batch_scores[$j]}" "${batch_descs[$j]}" "$dt"
        else
            cap_retries
            retry_and_harvest "${batch_ranks[$j]}" "$name" "${batch_scores[$j]}" "${batch_descs[$j]}" "$dt" &
            RETRY_PIDS+=("$!")
        fi
    done
done

log "=== waiting on background retries that haven't finished yet ==="
for pid in "${RETRY_PIDS[@]}"; do
    wait "$pid" 2>/dev/null
done

log "=== FINISHED (or budget exhausted) ==="
log "report: $STATUS"
column -t -s $'\t' "$STATUS" | tee -a "$LOG"
